version: '3'
services:
  backend:
    build: ./api
    container_name: api-flask
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
        - "27017:27017"

